In [1]:
x = matrix (nrow = 4 , ncol = 3 , data =c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [4]:
rownames(x) = c("r1" , "r2" , "r3" , "r4")
x
colnames(x) = c("c1", "c2", "c3")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

Assigning a specified number to all matrix elements:

In [6]:
x = matrix( nrow = 4 , ncol = 2 , data = 2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

Construction of a diagonal matrix, here the identity matrix of a
dimension 3

In [9]:
d = diag(1 , nrow=3 , ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

Construction of a diagonal matrix with all numbers as 5 of a
dimension 3:

In [10]:
d - diag(5 , nrow=3 , ncol=3)
d

     [,1] [,2] [,3]
[1,] -4    0    0
[2,]  0   -4    0
[3,]  0    0   -4

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

Transpose of a matrix X

In [11]:
x = matrix(nrow=4 , ncol=2 , data=1:8 , byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [12]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Finding the row and column sums

In [15]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [16]:
rowSums(x)

[1]  6  8 10 12

In [19]:
colSums(x)

[1] 10 26

In [20]:
 x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
 x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [21]:
rowMeans(x)
colMeans(x)

[1] 3 4 5 6

[1] 2.5 6.5

Access to rows, columns or submatrices

In [22]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [25]:
x[3,]
x[,2]
x[4:5 , 2:3]

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [26]:
x[c(1,4) , c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [27]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

Addition of a matrix with a constant

In [28]:
x = matrix(nrow = 4 , ncol = 2 , data = 1:8 , byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

Subtraction of a matrix with a constant

In [29]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

Multiplication of a matrix with a constan

In [32]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
5*x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

Division of a matrix with a constant

In [33]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Addition and subtraction of matrices

In [36]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [37]:
x+y
x-y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [38]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [39]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [41]:
x+4*x
4*x-x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

Multiplication of matrices

In [43]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [44]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [46]:
 x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
 t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [49]:
t(x) %*% x
x %*% t(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [50]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [51]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [52]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Concatenating matrices

In [55]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
rbind(x,y)
cbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

Inverse of matrix

In [59]:
y = matrix( nrow = 2, ncol = 2, byrow = T , data = c(84,100,100,120))
y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

Eigen values and eigen vectors of matrix

In [64]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data
= c(84,100,100,120))
y
eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [67]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [70]:
x = c(8,18)
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [72]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [74]:
x = 15
(x < 10) && (x>2)

[1] FALSE

In [77]:
x = c(8,18)
(x<10) & (x>2)

[1]  TRUE FALSE

In [80]:
x = TRUE
y = TRUE

x & y
x|y
!x

[1] TRUE

[1] TRUE

[1] FALSE

In [83]:
x = 5
Logical1 = (x > 2)
Logical1
is.logical(Logical1)

[1] TRUE

[1] TRUE

In [84]:
Logical2 = (x < 10)
Logical2
is.logical(Logical2)

[1] TRUE

[1] TRUE

In [88]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x>y
x<y
x!=y
x==y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [86]:
isTRUE(8 < 6)

[1] FALSE

In [87]:
 isTRUE(8 > 6)

[1] TRUE